version: 2

jobs:
  unit_test:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      - run: npm install
        
      # run tests!
      - run: npm test

  e2e_test:

    machine: true

    working_directory: ~/repo

    steps:

      - checkout

      - run: npm install

      - run: npm run build

       # build  Docker image
      - run: |
          TAG=$CIRCLE_BUILD_NUM
          USERNAME=philipmorrisdev
          REPO=ui
          docker build -t $USERNAME/$REPO:$TAG .
          docker run -d -p 3000:3000 $USERNAME/$REPO:$TAG

      # This should go into custom primary image, here's only for the sake of explanation
      - run:
          name: Install Cypress
          command: |
            set -x
            npm install cypress -g

      - run:
          name: Running E2E tests
          command: cypress run

  deployment:
    docker:
      - image: efficienthealth/node-awscli:latest

    steps:

      - checkout

      - run: npm install

      - run: npm run build

      - deploy:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
              aws s3 sync ./build s3://philipmorrisdev --delete --region eu-west-2 --acl public-read

#   if [ "${CIRCLE_BRANCH}" == "master" ]; then
#               aws s3 sync ./build s3://philipmorrisdev --delete --region eu-west-2 --acl public-read
#             else
#               echo "Not master branch so not deploying"
#             fi

workflows:

  version: 2
  
  test_and_deploy:

    jobs:

      #- unit_test
      
      - e2e_test
      #    requires:
      #      - unit_test
      
      #- deployment:
      #    requires:
      #      - e2e_test