# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  unit_test:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      - run: npm test

  e2e_test:
    docker:
      # the Docker image with Cypress preinstalled
      - image: cypress/internal:cy-0.19.4
        environment:
          ## this enables colors in the output
          TERM: xterm
    working_directory: ~/app
    parallelism: 1
    steps:
      - checkout
      - run: npm install
      - run:
          name: Running E2E tests with JUnit reporter
          command: npm run test-junit
      - store_test_results:
          path: junit-results
      - run:
          name: Running E2E tests with multiple reporters
          command: npm run test-multiple
      - store_test_results:
          path: multiple-results
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

  deployment:
    staging:
      branch: master
      heroku:
        appname: philipmorrisdev

workflows:
  version: 2
  test:
    jobs:
      - unit_test
      - e2e_test
      - deployment